In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,accuracy_score
from sklearn.preprocessing import MinMaxScaler
df=pd.read_csv(r"C:\Users\MathanVini\Downloads\archive (3)\california_housing_test_1.csv")
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,Unnamed: 9,ocean_proximity
0,-122.05,37.37,27,3885,661,1537,606,6.6085,344700,NaN,NEAR BAY
1,-118.30,34.26,43,1510,310,809,277,3.5990,176500,NaN,NEAR BAY
2,-117.81,33.78,27,3589,507,1484,495,5.7934,270500,NaN,NEAR BAY
3,-118.36,33.82,28,67,15,49,11,6.1359,330000,NaN,NEAR BAY
4,-119.67,36.33,19,1241,244,850,237,2.9375,81700,NaN,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23,1450,642,1258,607,1.1790,225000,NaN,NaN
2996,-118.14,34.06,27,5257,1082,3496,1036,3.3906,237200,NaN,NaN
2997,-119.70,36.30,10,956,201,693,220,2.2895,62000,NaN,NaN
2998,-117.12,34.10,40,96,14,46,14,3.2708,162500,NaN,NaN
2999,-119.63,34.42,42,1765,263,753,260,8.5608,500001,NaN,NaN

In [2]:
df=df.drop('ocean_proximity',axis=1)
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,Unnamed: 9
0,-122.05,37.37,27,3885,661,1537,606,6.6085,344700,NaN
1,-118.30,34.26,43,1510,310,809,277,3.5990,176500,NaN
2,-117.81,33.78,27,3589,507,1484,495,5.7934,270500,NaN
3,-118.36,33.82,28,67,15,49,11,6.1359,330000,NaN
4,-119.67,36.33,19,1241,244,850,237,2.9375,81700,NaN
...,...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23,1450,642,1258,607,1.1790,225000,NaN
2996,-118.14,34.06,27,5257,1082,3496,1036,3.3906,237200,NaN
2997,-119.70,36.30,10,956,201,693,220,2.2895,62000,NaN
2998,-117.12,34.10,40,96,14,46,14,3.2708,162500,NaN
2999,-119.63,34.42,42,1765,263,753,260,8.5608,500001,NaN

In [3]:
df=df.drop('Unnamed: 9',axis=1)
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27,3885,661,1537,606,6.6085,344700
1,-118.30,34.26,43,1510,310,809,277,3.5990,176500
2,-117.81,33.78,27,3589,507,1484,495,5.7934,270500
3,-118.36,33.82,28,67,15,49,11,6.1359,330000
4,-119.67,36.33,19,1241,244,850,237,2.9375,81700
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23,1450,642,1258,607,1.1790,225000
2996,-118.14,34.06,27,5257,1082,3496,1036,3.3906,237200
2997,-119.70,36.30,10,956,201,693,220,2.2895,62000
2998,-117.12,34.10,40,96,14,46,14,3.2708,162500
2999,-119.63,34.42,42,1765,263,753,260,8.5608,500001

In [4]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   int64
 3   total_rooms         3000 non-null   int64
 4   total_bedrooms      3000 non-null   int64
 5   population          3000 non-null   int64
 6   households          3000 non-null   int64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   int64
dtypes: float64(3), int64(6)
memory usage: 211.1 KB

In [6]:
X=df.drop("median_house_value",axis=1)

In [7]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,3000.000000,3000.00000,3000.000000,3000.000000,3000.000000,3000.000000,3000.00000,3000.000000,3000.00000
mean,-119.589200,35.63539,28.845333,2599.578667,529.950667,1402.798667,489.91200,3.807272,205846.27500
std,1.994936,2.12967,12.555396,2155.593332,415.654368,1030.543012,365.42271,1.854512,113119.68747
min,-124.180000,32.56000,1.000000,6.000000,2.000000,5.000000,2.00000,0.499900,22500.00000
25%,-121.810000,33.93000,18.000000,1401.000000,291.000000,780.000000,273.00000,2.544000,121200.00000
50%,-118.485000,34.27000,29.000000,2106.000000,437.000000,1155.000000,409.50000,3.487150,177650.00000
75%,-118.020000,37.69000,37.000000,3129.000000,636.000000,1742.750000,597.25000,4.656475,263975.00000
max,-114.490000,41.92000,52.000000,30450.000000,5419.000000,11935.000000,4930.00000,15.000100,500001.00000

In [8]:
y=df["median_house_value"]
y

0       344700
1       176500
2       270500
3       330000
4        81700
         ...
2995    225000
2996    237200
2997     62000
2998    162500
2999    500001
Name: median_house_value, Length: 3000, dtype: int64

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [10]:
sc=MinMaxScaler()
sc.fit(X_train)
X_train=sc.transform(X_train)
X_test=sc.transform(X_test)
y_train=sc.fit_transform(y_train.values.reshape(-1,1))
y_test=sc.fit_transform(y_test.values.reshape(-1,1))

In [11]:
y_test[1]

array([0.12065191])

In [12]:
a = X_test[1]
a=a.reshape(1,-1)
a

array([[0.53099174, 0.38141026, 0.45098039, 0.07400473, 0.07494923,
        0.09756915, 0.07974838, 0.0834954 ]])

In [13]:
model=LinearRegression()

In [14]:
model.fit(X_train,y_train)

LinearRegression()

In [15]:
m=model.predict(a)
m

array([[0.08742678]])

In [22]:


y_test = y_test.ravel()  # Converts (600, 1) â†’ (600,)

In [24]:
m = model.predict(X_test)  # Ensure it outputs (600, 1)
m = m.ravel()  # Convert (600,1) â†’ (600,)

In [25]:
print("Shape of m before reshaping:", m.shape)

Shape of m before reshaping: (600,)

In [26]:
print("Shape of y_test:", y_test.shape)
print("Shape of m:", m.shape)

Shape of y_test: (600,)
Shape of m: (600,)

In [27]:
m = m.reshape(-1)  # Ensure it's a 1D array
mae = mean_absolute_error(y_test, m)
print("Mean Absolute Error:", mae)

Mean Absolute Error: 0.11983086180230129

In [ ]:
#user input given

In [35]:

input_data = np.array([[-122.05, 37.37, 27, 3885, 661, 1537, 606, 6.6085]])  # Example values

In [36]:
# Predict house price
predicted_price = model.predict(input_data)
print("Predicted House Price:", predicted_price[0])

Predicted House Price: [-2746.12756727]

In [28]:
mean_absolute_error(y_test,m)

0.11983086180230129

In [29]:
mean_squared_error(y_test,m)

0.02517689521279241